### ISSUE TITLE
UOIF Calculation Method

### ISSUE THREAD

**Issue by z3bi** [arabeyes-org/ITL#15]
One of the users of my prayer time app recently requested the addition of the UOIF calculation method as it is the predominant method in France. Doing some research, I found this article explaining their position http://www.uoif-online.com/pourquoi-le-12eme-degre-de-latitude-pour-determiner-lhoraire-du-ichaa-du-soubh/

They are using 12 degrees for Fajr and Isha in order to create more reasonable times. I was wondering if anyone had any input on whether this method should be added to the available calculations methods in the library.

**Comment by iTarek** [comment]
Yes it should be added
